/*
    @Version 10.10.13
    @Author: Tim Grunshaw
    This is the initial script to build the trademe_data database. It has already
    had the item, company etc tables removed. 

*/

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


CREATE TABLE BIDPAGES (ID INTEGER NOT NULL, DTYPE VARCHAR(31), PAGE INTEGER, PAGESIZE INTEGER, TOTALCOUNT INTEGER, PRIMARY KEY (ID));
CREATE TABLE BID (ID INTEGER NOT NULL, ACCOUNT VARCHAR(255), BIDAMOUNT DECIMAL(10,2), BIDDATE DATETIME, ISBUYNOW TINYINT(1) default 0, ISBYMOBILE TINYINT(1) default 0, ISBYPROXY TINYINT(1) default 0, BIDDER_MEMBERID INTEGER, PRIMARY KEY (ID));
CREATE TABLE QUESTIONPAGES (ID INTEGER NOT NULL, DTYPE VARCHAR(31), PAGE INTEGER, PAGESIZE INTEGER, TOTALCOUNT INTEGER, PRIMARY KEY (ID));
CREATE TABLE ATTRIBUTEOPTION (ID INTEGER NOT NULL, DISPLAY VARCHAR(255), VALUE VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE GEOGRAPHICLOCATION (ID INTEGER NOT NULL, ACCURACY INTEGER, EASTING INTEGER, LATITUDE DOUBLE, LONGITUDE DOUBLE, NORTHING INTEGER, PRIMARY KEY (ID));
CREATE TABLE PHOTO (PHOTOID INTEGER NOT NULL, FULLSIZE VARCHAR(255), GALLERY VARCHAR(255), LARGE VARCHAR(255), LIST VARCHAR(255), MEDIUM VARCHAR(255), URL_PHOTOID INTEGER, THUMBNAIL VARCHAR(255), PRIMARY KEY (PHOTOID));
CREATE TABLE OPENHOME (ID INTEGER NOT NULL, END DATETIME, START DATETIME, PRIMARY KEY (ID));
CREATE TABLE ATTRIBUTEUNIT (ID INTEGER NOT NULL, DISPLAY VARCHAR(255), MULTIPLIER DECIMAL(38), PRIMARY KEY (ID));
CREATE TABLE SHIPPINGOPTION (ID INTEGER NOT NULL, METHOD VARCHAR(255), PRICE DECIMAL(38), SHIPPINGID INTEGER, TYPE VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE ATTRIBUTE (ID INTEGER NOT NULL, DISPLAYNAME VARCHAR(255), ISREQUIREDFORSELL TINYINT(1) default 0, NAME VARCHAR(255), TYPE VARCHAR(255), VALUE VARCHAR(255), LOWER VARCHAR(255), UPPER VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE AGENCY (ID INTEGER NOT NULL, ADDRESS VARCHAR(255), AGENTS LONGBLOB, BILLINGTYPE INTEGER, CITY VARCHAR(255), EMAIL VARCHAR(255), FAXNUMBER VARCHAR(255), ISJOBAGENCY TINYINT(1) default 0, ISLICENSEDPROPERTYAGENCY TINYINT(1) default 0, ISREALESTATEAGENCY TINYINT(1) default 0, LOGO VARCHAR(255), NAME VARCHAR(255), PHONENUMBER VARCHAR(255), SUBURB VARCHAR(255), TYPE INTEGER, WEBSITE VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE LISTEDITEMDETAIL (LISTINGID INTEGER NOT NULL, ALLOWSPICKUPS VARCHAR(255), ASAT DATETIME, AUTHENTICATEDMEMBERSONLY TINYINT(1) default 0, BIDCOUNT INTEGER, BIDDERANDWATCHERS INTEGER, BODY VARCHAR(2048), BUYNOWPRICE DECIMAL(10,2), CATEGORY VARCHAR(255), CATEGORYNAME VARCHAR(255), CATEGORYPATH VARCHAR(255), ENDDATE DATETIME, HASBUYNOW TINYINT(1) default 0, HASEXTRAPHOTOS TINYINT(1) default 0, HASGALLERY TINYINT(1) default 0, HASHOMEPAGEFEATURE TINYINT(1) default 0, HASMULTIPLE TINYINT(1) default 0, HASPAYNOW TINYINT(1) default 0, HASRESERVE TINYINT(1) default 0, HASSCHEDULEDENDDATE TINYINT(1) default 0, ISBOLD TINYINT(1) default 0, ISBUYNOWONLY TINYINT(1) default 0, ISCLASSIFIED TINYINT(1) default 0, ISFEATURED TINYINT(1) default 0, ISFLATSHIPPINGCHARGE TINYINT(1) default 0, ISHIGHLIGHTED TINYINT(1) default 0, ISNEW TINYINT(1) default 0, ISORNEAROFFER TINYINT(1) default 0, ISRESERVEMET TINYINT(1) default 0, LISTINGLENGTH VARCHAR(255), MAXBIDAMOUNT DECIMAL(10,2), MINIMUMNEXTBIDAMOUNT DECIMAL(38), NOTE VARCHAR(255), NOTEDATE DATETIME, NOTEID INTEGER, PAYMENTOPTIONS VARCHAR(255), PHOTOID INTEGER, PICTUREHREF VARCHAR(255), POSITIVEREVIEWCOUNT INTEGER, PRICEDISPLAY VARCHAR(255), REGION VARCHAR(255), REGIONID INTEGER, RELISTEDITEMID INTEGER, RESERVEPRICE DECIMAL(10,2), RESERVESTATE VARCHAR(255), RESTRICTIONS VARCHAR(255), STARTDATE DATETIME, STARTPRICE DECIMAL(10,2), SUBTITLE VARCHAR(255), SUBURB VARCHAR(255), SUBURBID INTEGER, TITLE VARCHAR(255), TOTALREVIEWCOUNT INTEGER, UNANSWEREDQUESTIONCOUNT INTEGER, VIDEOURL VARCHAR(255), VIEWCOUNT INTEGER, BESTCONTACTTIME VARCHAR(255), CONTACTNAME VARCHAR(255), MOBILEPHONENUMBER VARCHAR(255), PHONENUMBER VARCHAR(255), MEMBER_MEMBERID INTEGER, AGENCY_ID INTEGER, BIDS_ID INTEGER, DEALERSHIP_ID INTEGER, GEOGRAPHICLOCATION_ID INTEGER, QUESTIONS_ID INTEGER, SELLER_MEMBERID INTEGER, PRIMARY KEY (LISTINGID));
CREATE TABLE QUESTION (LISTINGQUESTIONID INTEGER NOT NULL, ANSWER VARCHAR(500), ANSWERDATE DATETIME, COMMENT VARCHAR(500), COMMENTDATE DATETIME, ISSELLERCOMMENT TINYINT(1) default 0, LISTINGID INTEGER, ASKINGMEMBER_MEMBERID INTEGER, PRIMARY KEY (LISTINGQUESTIONID));
CREATE TABLE MEMBER (MEMBERID INTEGER NOT NULL, DATEADDRESSVERIFIED DATETIME, DATEJOINED DATETIME, EMAIL VARCHAR(255), FEEDBACKCOUNT INTEGER, ISADDRESSVERIFIED TINYINT(1) default 0, ISAUTHENTICATED TINYINT(1) default 0, ISDEALER TINYINT(1) default 0, NICKNAME VARCHAR(255), REGION VARCHAR(255), REGIONID INTEGER, SUBURB VARCHAR(255), SUBURBID INTEGER, UNIQUENEGATIVE INTEGER, UNIQUEPOSITIVE INTEGER, PRIMARY KEY (MEMBERID));
CREATE TABLE DEALERSHIP (ID INTEGER NOT NULL, ADDRESS VARCHAR(255), BILLINGTYPE INTEGER, CITY VARCHAR(255), DEALERS LONGBLOB, EMAIL VARCHAR(255), FAXNUMBER VARCHAR(255), LOGO VARCHAR(255), NAME VARCHAR(255), PHONENUMBER VARCHAR(255), SUBURB VARCHAR(255), TYPE INTEGER, WEBSITE VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE INVALIDLISTING (LISTINGID INTEGER NOT NULL, LISTINGERROR VARCHAR(255), PRIMARY KEY (LISTINGID));
CREATE TABLE QUESTIONPAGES_QUESTION (QuestionPages_ID INTEGER NOT NULL, list_LISTINGQUESTIONID INTEGER NOT NULL, PRIMARY KEY (QuestionPages_ID, list_LISTINGQUESTIONID));
CREATE TABLE BIDPAGES_BID (BidPages_ID INTEGER NOT NULL, list_ID INTEGER NOT NULL, PRIMARY KEY (BidPages_ID, list_ID));
CREATE TABLE ATTRIBUTE_ATTRIBUTEOPTION (Attribute_ID INTEGER NOT NULL, options_ID INTEGER NOT NULL, PRIMARY KEY (Attribute_ID, options_ID));
CREATE TABLE ATTRIBUTE_ATTRIBUTEUNIT (Attribute_ID INTEGER NOT NULL, units_ID INTEGER NOT NULL, PRIMARY KEY (Attribute_ID, units_ID));
CREATE TABLE LISTEDITEMDETAIL_ATTRIBUTE (ListedItemDetail_LISTINGID INTEGER NOT NULL, attributes_ID INTEGER NOT NULL, PRIMARY KEY (ListedItemDetail_LISTINGID, attributes_ID));
CREATE TABLE LISTEDITEMDETAIL_OPENHOME (ListedItemDetail_LISTINGID INTEGER NOT NULL, openHomes_ID INTEGER NOT NULL, PRIMARY KEY (ListedItemDetail_LISTINGID, openHomes_ID));
CREATE TABLE LISTEDITEMDETAIL_PHOTO (ListedItemDetail_LISTINGID INTEGER NOT NULL, photos_PHOTOID INTEGER NOT NULL, PRIMARY KEY (ListedItemDetail_LISTINGID, photos_PHOTOID));
CREATE TABLE LISTEDITEMDETAIL_SHIPPINGOPTION (ListedItemDetail_LISTINGID INTEGER NOT NULL, shippingOptions_ID INTEGER NOT NULL, PRIMARY KEY (ListedItemDetail_LISTINGID, shippingOptions_ID));
ALTER TABLE BID ADD CONSTRAINT FK_BID_BIDDER_MEMBERID FOREIGN KEY (BIDDER_MEMBERID) REFERENCES MEMBER (MEMBERID);
ALTER TABLE LISTEDITEMDETAIL ADD CONSTRAINT FK_LISTEDITEMDETAIL_GEOGRAPHICLOCATION_ID FOREIGN KEY (GEOGRAPHICLOCATION_ID) REFERENCES GEOGRAPHICLOCATION (ID);
ALTER TABLE LISTEDITEMDETAIL ADD CONSTRAINT FK_LISTEDITEMDETAIL_AGENCY_ID FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY (ID);
ALTER TABLE LISTEDITEMDETAIL ADD CONSTRAINT FK_LISTEDITEMDETAIL_QUESTIONS_ID FOREIGN KEY (QUESTIONS_ID) REFERENCES QUESTIONPAGES (ID);
ALTER TABLE LISTEDITEMDETAIL ADD CONSTRAINT FK_LISTEDITEMDETAIL_BIDS_ID FOREIGN KEY (BIDS_ID) REFERENCES BIDPAGES (ID);
ALTER TABLE LISTEDITEMDETAIL ADD CONSTRAINT FK_LISTEDITEMDETAIL_SELLER_MEMBERID FOREIGN KEY (SELLER_MEMBERID) REFERENCES MEMBER (MEMBERID);
ALTER TABLE LISTEDITEMDETAIL ADD CONSTRAINT FK_LISTEDITEMDETAIL_DEALERSHIP_ID FOREIGN KEY (DEALERSHIP_ID) REFERENCES DEALERSHIP (ID);
ALTER TABLE LISTEDITEMDETAIL ADD CONSTRAINT FK_LISTEDITEMDETAIL_MEMBER_MEMBERID FOREIGN KEY (MEMBER_MEMBERID) REFERENCES MEMBER (MEMBERID);
ALTER TABLE QUESTION ADD CONSTRAINT FK_QUESTION_ASKINGMEMBER_MEMBERID FOREIGN KEY (ASKINGMEMBER_MEMBERID) REFERENCES MEMBER (MEMBERID);
ALTER TABLE QUESTIONPAGES_QUESTION ADD CONSTRAINT FK_QUESTIONPAGES_QUESTION_list_LISTINGQUESTIONID FOREIGN KEY (list_LISTINGQUESTIONID) REFERENCES QUESTION (LISTINGQUESTIONID);
ALTER TABLE QUESTIONPAGES_QUESTION ADD CONSTRAINT FK_QUESTIONPAGES_QUESTION_QuestionPages_ID FOREIGN KEY (QuestionPages_ID) REFERENCES QUESTIONPAGES (ID);
ALTER TABLE BIDPAGES_BID ADD CONSTRAINT FK_BIDPAGES_BID_BidPages_ID FOREIGN KEY (BidPages_ID) REFERENCES BIDPAGES (ID);
ALTER TABLE BIDPAGES_BID ADD CONSTRAINT FK_BIDPAGES_BID_list_ID FOREIGN KEY (list_ID) REFERENCES BID (ID);
ALTER TABLE ATTRIBUTE_ATTRIBUTEOPTION ADD CONSTRAINT FK_ATTRIBUTE_ATTRIBUTEOPTION_Attribute_ID FOREIGN KEY (Attribute_ID) REFERENCES ATTRIBUTE (ID);
ALTER TABLE ATTRIBUTE_ATTRIBUTEOPTION ADD CONSTRAINT FK_ATTRIBUTE_ATTRIBUTEOPTION_options_ID FOREIGN KEY (options_ID) REFERENCES ATTRIBUTEOPTION (ID);
ALTER TABLE ATTRIBUTE_ATTRIBUTEUNIT ADD CONSTRAINT FK_ATTRIBUTE_ATTRIBUTEUNIT_units_ID FOREIGN KEY (units_ID) REFERENCES ATTRIBUTEUNIT (ID);
ALTER TABLE ATTRIBUTE_ATTRIBUTEUNIT ADD CONSTRAINT FK_ATTRIBUTE_ATTRIBUTEUNIT_Attribute_ID FOREIGN KEY (Attribute_ID) REFERENCES ATTRIBUTE (ID);
ALTER TABLE LISTEDITEMDETAIL_ATTRIBUTE ADD CONSTRAINT FK_LISTEDITEMDETAIL_ATTRIBUTE_attributes_ID FOREIGN KEY (attributes_ID) REFERENCES ATTRIBUTE (ID);
ALTER TABLE LISTEDITEMDETAIL_ATTRIBUTE ADD CONSTRAINT LISTEDITEMDETAILATTRIBUTEListedItemDetailLISTINGID FOREIGN KEY (ListedItemDetail_LISTINGID) REFERENCES LISTEDITEMDETAIL (LISTINGID);
ALTER TABLE LISTEDITEMDETAIL_OPENHOME ADD CONSTRAINT FK_LISTEDITEMDETAIL_OPENHOME_openHomes_ID FOREIGN KEY (openHomes_ID) REFERENCES OPENHOME (ID);
ALTER TABLE LISTEDITEMDETAIL_OPENHOME ADD CONSTRAINT LISTEDITEMDETAILOPENHOMEListedItemDetail_LISTINGID FOREIGN KEY (ListedItemDetail_LISTINGID) REFERENCES LISTEDITEMDETAIL (LISTINGID);
ALTER TABLE LISTEDITEMDETAIL_PHOTO ADD CONSTRAINT LISTEDITEMDETAIL_PHOTO_ListedItemDetail_LISTINGID FOREIGN KEY (ListedItemDetail_LISTINGID) REFERENCES LISTEDITEMDETAIL (LISTINGID);
ALTER TABLE LISTEDITEMDETAIL_PHOTO ADD CONSTRAINT FK_LISTEDITEMDETAIL_PHOTO_photos_PHOTOID FOREIGN KEY (photos_PHOTOID) REFERENCES PHOTO (PHOTOID);
ALTER TABLE LISTEDITEMDETAIL_SHIPPINGOPTION ADD CONSTRAINT LSTDTEMDETAILSHIPPINGOPTIONLstdItemDetailLISTINGID FOREIGN KEY (ListedItemDetail_LISTINGID) REFERENCES LISTEDITEMDETAIL (LISTINGID);
ALTER TABLE LISTEDITEMDETAIL_SHIPPINGOPTION ADD CONSTRAINT LISTEDITEMDETAIL_SHIPPINGOPTION_shippingOptions_ID FOREIGN KEY (shippingOptions_ID) REFERENCES SHIPPINGOPTION (ID);
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);


/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;