/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `attribute_attributeunit` (
  `Attribute_ID` int(11) NOT NULL,
  `units_ID` int(11) NOT NULL,
  PRIMARY KEY (`Attribute_ID`,`units_ID`),
  KEY `FK_ATTRIBUTE_ATTRIBUTEUNIT_units_ID` (`units_ID`),
  CONSTRAINT `FK_ATTRIBUTE_ATTRIBUTEUNIT_Attribute_ID` FOREIGN KEY (`Attribute_ID`) REFERENCES `attribute` (`ID`),
  CONSTRAINT `FK_ATTRIBUTE_ATTRIBUTEUNIT_units_ID` FOREIGN KEY (`units_ID`) REFERENCES `attributeunit` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `attributeunit` (
  `ID` int(11) NOT NULL,
  `DISPLAY` varchar(255) DEFAULT NULL,
  `MULTIPLIER` decimal(38,0) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



ALTER TABLE listeditemdetail ADD positivereviewcount int(11) DEFAULT NULL AFTER picturehref;
ALTER TABLE listeditemdetail ADD totalreviewcount int(11) DEFAULT NULL AFTER title;


/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
