/*
    @Version 31.10.13
    @Author: Tim Grunshaw
    This is the initial build script for the TradeIntel database as per 
    EclipseLink generation.

*/

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE APICREDENTIALS (ACCESSTOKEN VARCHAR(255) NOT NULL, DTYPE VARCHAR(31), ACCESSSECRET VARCHAR(255), CONSUMERKEY VARCHAR(255), CONSUMERSECRET VARCHAR(255), DATEADDED DATETIME, DATETIMELIMITWASREACHED DATETIME, EMAILADDRESS VARCHAR(255), FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), NICKNAME VARCHAR(255), NUMBEROFCALLSUSED INTEGER, USEDBY VARCHAR(255), PRIMARY KEY (ACCESSTOKEN));
CREATE TABLE users (ID INTEGER NOT NULL, DATEEMAILCHANGED DATETIME, EMAIL VARCHAR(255) NOT NULL UNIQUE, NEWEMAIL VARCHAR(255), PASSWORD LONGTEXT NOT NULL, SALT LONGTEXT NOT NULL, AUTORENEW TINYINT(1) default 0 NOT NULL, CONTACTNUMBER1 VARCHAR(255), CONTACTNUMBER2 VARCHAR(255), FIRSTNAME VARCHAR(255) NOT NULL, FIRSTREGISTERED DATETIME, ISVERIFIED TINYINT(1) default 0 NOT NULL, LASTNAME VARCHAR(255) NOT NULL, SUBSCRIPTIONEXPIRES DATETIME NOT NULL, SUBSCRIPTIONTYPE VARCHAR(255) NOT NULL, VERIFICATION_KEY VARCHAR(255) NOT NULL, CITY VARCHAR(255), POSTCODE VARCHAR(255), STREET1 VARCHAR(255), STREET2 VARCHAR(255), APICREDENTIAL_ACCESSTOKEN VARCHAR(255), USERDATA_ID BIGINT, USERPREFERENCES_ID BIGINT, USERPAYMENTINFO_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE USERPREFERENCES (ID BIGINT NOT NULL, STARTTABINDEX INTEGER NOT NULL, PRIMARY KEY (ID));
CREATE TABLE USERDATA (ID BIGINT NOT NULL, PRIMARY KEY (ID));
CREATE TABLE LISTINGSEARCH (ID BIGINT NOT NULL, CATEGORYPATH VARCHAR(255), EARLIESTENDDATE DATETIME, HIGHESTPRICE DECIMAL(38), ISBODYSEARCHED TINYINT(1) default 0, ISBUYNOWREQUIRED TINYINT(1) default 0, ISPAYNOWREQUIRED TINYINT(1) default 0, ISSOLD TINYINT(1) default 0, LATESTENDDATE DATETIME, LOWESTPRICE DECIMAL(38), RESULTCOUNT INTEGER, SEARCHTERMS VARCHAR(255), SEARCHTYPE VARCHAR(255), THECONDITION VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE USERPAYMENTINFO (ID BIGINT NOT NULL, DPSBILLINGID VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE PAYMENTTRANSACTION (TRANSACTIONID BIGINT AUTO_INCREMENT NOT NULL, AUTOTRANSACTION TINYINT(1) default 0 NOT NULL, TRANSACTIONDATE DATETIME NOT NULL, TRANSACTIONRESPONSE_ID BIGINT, PRIMARY KEY (TRANSACTIONID));
CREATE TABLE RESPONSE (ID BIGINT NOT NULL, AMOUNTSETTLEMENT VARCHAR(255), AUTHCODE VARCHAR(255), BILLINGID VARCHAR(255), CARDHOLDERNAME VARCHAR(255), CARDNAME VARCHAR(255), CARDNUMBER VARCHAR(255), CARDNUMBER2 VARCHAR(255), CLIENTINFO VARCHAR(255), CURRENCYINPUT VARCHAR(255), CURRENCYSETTLEMENT VARCHAR(255), DATEEXPIRY VARCHAR(255), DPSBILLINGID VARCHAR(255), DPSTXNREF VARCHAR(255), EMAILADDRESS VARCHAR(255), MERCHANTREFERENCE VARCHAR(255), RESPONSETEXT VARCHAR(255), SUCCESS VARCHAR(255), TXNDATA1 VARCHAR(255), TXNDATA2 VARCHAR(255), TXNDATA3 VARCHAR(255), TXNID VARCHAR(255), TXNMAC VARCHAR(255), TXNTYPE VARCHAR(255), VALID VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE TRACKEDPRODUCT (ID BIGINT NOT NULL, LASTUPDATED DATETIME, MAXSTATVALUE DOUBLE, MINSTATVALUE DOUBLE, PERIODCOUNT INTEGER, PERIODTYPE VARCHAR(255), STATISTICCLASSNAME VARCHAR(255), TOEMAIL TINYINT(1) default 0, SEARCH_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE EMAIL (ID VARCHAR(255) NOT NULL, BODY VARCHAR(4096), SUBJECT VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE RESETPASSWORD (HASHEDUUID VARCHAR(64) NOT NULL, RESETPASSWORDUSED TINYINT(1) default 0, TIMERESET DATETIME, PASSWORDRESETS_ID INTEGER, PRIMARY KEY (HASHEDUUID));
CREATE TABLE users_groups (email VARCHAR(255) NOT NULL, groupname VARCHAR(255) NOT NULL);
CREATE TABLE USERDATA_LISTINGSEARCH (UserData_ID BIGINT NOT NULL, savedSearches_ID BIGINT NOT NULL, PRIMARY KEY (UserData_ID, savedSearches_ID));
CREATE TABLE USERDATA_TRACKEDPRODUCT (UserData_ID BIGINT NOT NULL, trackedProducts_ID BIGINT NOT NULL, PRIMARY KEY (UserData_ID, trackedProducts_ID));
CREATE TABLE USERPAYMENTINFO_PAYMENTTRANSACTION (UserPaymentInfo_ID BIGINT NOT NULL, transactions_TRANSACTIONID BIGINT NOT NULL, PRIMARY KEY (UserPaymentInfo_ID, transactions_TRANSACTIONID));
ALTER TABLE users ADD CONSTRAINT FK_users_USERDATA_ID FOREIGN KEY (USERDATA_ID) REFERENCES USERDATA (ID);
ALTER TABLE users ADD CONSTRAINT FK_users_USERPAYMENTINFO_ID FOREIGN KEY (USERPAYMENTINFO_ID) REFERENCES USERPAYMENTINFO (ID);
ALTER TABLE users ADD CONSTRAINT FK_users_USERPREFERENCES_ID FOREIGN KEY (USERPREFERENCES_ID) REFERENCES USERPREFERENCES (ID);
ALTER TABLE users ADD CONSTRAINT FK_users_APICREDENTIAL_ACCESSTOKEN FOREIGN KEY (APICREDENTIAL_ACCESSTOKEN) REFERENCES APICREDENTIALS (ACCESSTOKEN);
ALTER TABLE PAYMENTTRANSACTION ADD CONSTRAINT FK_PAYMENTTRANSACTION_TRANSACTIONRESPONSE_ID FOREIGN KEY (TRANSACTIONRESPONSE_ID) REFERENCES RESPONSE (ID);
ALTER TABLE TRACKEDPRODUCT ADD CONSTRAINT FK_TRACKEDPRODUCT_SEARCH_ID FOREIGN KEY (SEARCH_ID) REFERENCES LISTINGSEARCH (ID);
ALTER TABLE RESETPASSWORD ADD CONSTRAINT FK_RESETPASSWORD_PASSWORDRESETS_ID FOREIGN KEY (PASSWORDRESETS_ID) REFERENCES users (ID);
ALTER TABLE users_groups ADD CONSTRAINT FK_users_groups_email FOREIGN KEY (email) REFERENCES users (EMAIL);
ALTER TABLE USERDATA_LISTINGSEARCH ADD CONSTRAINT FK_USERDATA_LISTINGSEARCH_savedSearches_ID FOREIGN KEY (savedSearches_ID) REFERENCES LISTINGSEARCH (ID);
ALTER TABLE USERDATA_LISTINGSEARCH ADD CONSTRAINT FK_USERDATA_LISTINGSEARCH_UserData_ID FOREIGN KEY (UserData_ID) REFERENCES USERDATA (ID);
ALTER TABLE USERDATA_TRACKEDPRODUCT ADD CONSTRAINT FK_USERDATA_TRACKEDPRODUCT_UserData_ID FOREIGN KEY (UserData_ID) REFERENCES USERDATA (ID);
ALTER TABLE USERDATA_TRACKEDPRODUCT ADD CONSTRAINT FK_USERDATA_TRACKEDPRODUCT_trackedProducts_ID FOREIGN KEY (trackedProducts_ID) REFERENCES TRACKEDPRODUCT (ID);
ALTER TABLE USERPAYMENTINFO_PAYMENTTRANSACTION ADD CONSTRAINT USERPAYMENTINFOPAYMENTTRANSACTIONUserPaymentInfoID FOREIGN KEY (UserPaymentInfo_ID) REFERENCES USERPAYMENTINFO (ID);
ALTER TABLE USERPAYMENTINFO_PAYMENTTRANSACTION ADD CONSTRAINT SRPYMNTINFOPAYMENTTRANSACTIONtrnsctnsTRANSACTIONID FOREIGN KEY (transactions_TRANSACTIONID) REFERENCES PAYMENTTRANSACTION (TRANSACTIONID);
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);


/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;